name: xctdiff
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - Default
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - cmake==3.27.5
    - einops==0.6.1
    - einops-exts==0.0.4
    - filelock==3.12.4
    - frozenlist==1.4.0
    - fsspec==2023.9.1
    - ftfy==6.1.1
    - future==0.18.3
    - google-auth==2.23.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.58.0
    - huggingface-hub==0.17.2
    - idna==3.4
    - imageio==2.31.3
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - jinja2==3.1.2
    - lazy-loader==0.3
    - lightning-utilities==0.9.0
    - lit==16.0.6
    - lpips==0.1.4
    - markdown==3.4.4
    - markupsafe==2.1.3
    - monai==1.2.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.1
    - nibabel==5.1.0
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open-clip-torch==2.0.2
    - packaging==23.1
    - pillow==10.0.1
    - protobuf==4.24.3
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydeprecate==0.3.1
    - pytorch-lightning==1.4.2
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - regex==2023.8.8
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rotary-embedding-torch==0.3.5
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.10.1
    - sympy==1.12
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - tifffile==2023.7.10
    - tokenizers==0.12.1
    - torch==2.0.1
    - torchmetrics==0.6.0
    - torchvision==0.15.2
    - tqdm==4.66.1
    - transformers==4.19.2
    - triton==2.0.0
    - typing-extensions==4.8.0
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - werkzeug==2.3.7
    - yarl==1.9.2
    - zipp==3.17.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
prefix: /home/first/.conda/envs/xctdiff
